######################################################################
# Automatically generated by qmake (3.0) ?? ??? 21 20:20:17 2014
######################################################################

TEMPLATE = app
TARGET = 2-debug
INCLUDEPATH += .

# Input
HEADERS += list.h plist.h ulist.h
SOURCES += plist.cpp ulist.cpp
